/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Visual.comprarEntrada;
import Visual.comprarEntrada;
import Visual.perfilTrabajador;
import Visual.perfilTrabajador;


public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        ///hacer el menu visible
        this.setVisible(true);
        ///poner el menu en el centro de la pantalla 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitCartelera = new javax.swing.JMenuItem();
        mitCompra = new javax.swing.JMenuItem();
        mitSalir = new javax.swing.JMenuItem();
        mitLogin = new javax.swing.JMenuItem();
        acercade = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("¡Bienvenido a CineStar!");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cine (1).png"))); // NOI18N

        jMenu1.setText("Opciones Cliente");
        jMenu1.setActionCommand("Opciones ");

        mitCartelera.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        mitCartelera.setText("Cartelera");
        mitCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitCarteleraActionPerformed(evt);
            }
        });
        jMenu1.add(mitCartelera);

        mitCompra.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        mitCompra.setText("Comprar entradas");
        mitCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitCompraActionPerformed(evt);
            }
        });
        jMenu1.add(mitCompra);

        mitSalir.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        mitSalir.setText("Salir");
        mitSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mitSalir);

        mitLogin.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        mitLogin.setText("Log In Empleados");
        mitLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitLoginActionPerformed(evt);
            }
        });
        jMenu1.add(mitLogin);

        jMenuBar1.add(jMenu1);

        acercade.setText("Acerca de");
        jMenuBar1.add(acercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitCarteleraActionPerformed
       //inicializar la cartelera al darle click a la opcion cartelera
        Cartelera c = new Cartelera();
    }//GEN-LAST:event_mitCarteleraActionPerformed

    private void mitCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitCompraActionPerformed
      //inicializar la cartelera al darle click a la opcion comprar entrada
        comprarEntrada ce = new comprarEntrada ();
    }//GEN-LAST:event_mitCompraActionPerformed

    private void mitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSalirActionPerformed
       ///Hacer que todo se cierre si el usuario presiona el boton de salir
        System.exit(0);    
    }//GEN-LAST:event_mitSalirActionPerformed

    private void mitLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitLoginActionPerformed
        //inicializar la cartelera al darle click a la opcion log in
        perfilTrabajador pt = new perfilTrabajador ();
    }//GEN-LAST:event_mitLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acercade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mitCartelera;
    private javax.swing.JMenuItem mitCompra;
    private javax.swing.JMenuItem mitLogin;
    private javax.swing.JMenuItem mitSalir;
    // End of variables declaration//GEN-END:variables
}
